# Generated by Django 5.0.6 on 2024-06-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_counties_options_alter_counties_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='dis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
