# Generated by Django 5.0.6 on 2024-06-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_counties_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='dis',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
